lang: en
link-citations: true
link-bibliography: true
nocite: "@*"
classoption: twoside
fontsize: "11pt"
mainfont: "Latin Modern Roman"
mainfontoptions:
- BoldFont=Technika-Regular
- BoldItalicFont=Technika-Italic
sansfont: "Technika"
sansfontoptions:
  - UprightFont = *-Light,
  - BoldFont = *-Regular,
  - ItalicFont = *-LightItalic,
  - BoldItalicFont = *-Italic,
numbersections: true
lof: true
toc: true
geometry:
- a4paper
- top=32mm
#- inner=35.6mm
#- outer=35.6mm
- inner=40.6mm
- outer=30.6mm
- bottom=30mm
autoSectionLabels: true