lang: en
link-citations: true
link-bibliography: true
nocite: "@*"
classoption: twoside,symmetric
fontsize: "11pt"
mainfont: "Latin Modern Roman"
mainfontoptions:
- BoldFont=Technika-Regular
- BoldItalicFont=Technika-Italic
sansfont: "Technika"
sansfontoptions:
  - UprightFont = *-Light,
  - BoldFont = *-Regular,
  - ItalicFont = *-LightItalic,
  - BoldItalicFont = *-Italic,
numbersections: true
lof: true
toc: true
geometry:
- a4paper
- top=32mm
- left=35.6mm
- right=35.6mm
- bottom=30mm
autoSectionLabels: true